### ISSUE TITLE
Show only owned game in Want To Play

### ISSUE THREAD

**Issue by junqdu** [gameshelf/gameshelf.github.io#27]
https://www.reddit.com/r/boardgames/comments/7rl2f6/17_days_ago_i_built_gameshelfgithubio_now_i_have/dsy4xi3/

**Comment by theanine** [comment]
This doesn't appear to be working for me.

**Comment by junqdu** [comment]
@theanine bggid?

**Comment by junqdu** [comment]
@theanine most the game you marked in your collection as "Want To Play" is owned. And if you look at the total count in the end of the list, it shows you how many item is displaying. Therefore, user error.

**Comment by theanine** [comment]
Hmm... something is strange, because it now appears to be working for me.  I assert that it was not "user error" that I was experiencing.  For example, I was specifically looking at "Food Chain Magnate" which is a game that I do not own but I do want to play.  After toggling the button, that game still appeared on the list when I previously reported.  Now it no longer shows up when I toggle the button.  Was something changed after I reported?  I tried many times before and it didn't work.  I just tried a few times and it's working every time.
