### ISSUE TITLE
Not working anymore?

### ISSUE THREAD

**Issue by curtca** [gameshelf/gameshelf.github.io#46]
This is/was a great tool. Is it still working? I can't get it to load my collection anymore. 

Also, the data is a year old (according to Help page). Can it be updated?

**Comment by curtca** [comment]
Actually the Clear Cache button worked (I could have sworn I tried that).

**Comment by curtca** [comment]
But would still love to have the data updated.

**Comment by junqdu** [comment]
@curtca 
Yea, I would like to get those data updated too, but due to changes they made in the backend, I can no longer export the "entire" collection, https://boardgamegeek.com/geekcollection.php?action=exportcsv&subtype=boardgame&username=Game%20Shelf&all=1

and the reason for
>Collection exceeds maximum export size

is that the limited the max to 14,500 items (https://boardgamegeek.com/article/32236037#32236037)

So the solution would be making about 109200/14500 = 8 accounts and re-add a section of the entire collection into each account and then export them individually. Not sure when I want to write the script to do that.

**Comment by curtca** [comment]
How about just the top N ranked games? (e.g. 5,000)
